app:
    resource: "@AppBundle/Controller/"
    type:     annotation
lucky_number:
    path:     /lucky/number/{count}
    defaults: { _controller: AppBundle:Lucky:number}
hello0:
    path:     /hello
    defaults: { _controller: AppBundle:Lucky:hello}
hello2:
    path:      /hello/{name}
    defaults:  { _controller: AppBundle:Hello:index }
hello:
    path:      /hello/{firstName}/{lastName}
    defaults:  { _controller: AppBundle:Hello:index }
blog_show:
    path:      /blog/{slug}
    defaults:  { _controller: AppBundle:Blog:show }
