app:
    resource: "@AppBundle/Controller/"
    type:     annotation
hello:
    path:      /hello/{name}
    defaults:  { _controller: AppBundle:Hello:index }
blog:
    path:      /blog
    defaults:  { _controller: AppBundle:Blog:index }